### ISSUE TITLE
Javadoc generation error

### ISSUE THREAD

**Issue by bertoso** [mnlipp/jdrupes-mdoclet#1]
I tried replacing Abnaxos' doclet with this one but when I run javadoc it generates the following errors:

javadoc: error - Error writing highlight.js: C:\Users\aheredia\cdcl\build\docs\javadoc\internal\highlight.pack.js: The process cannot access the file because it is being used by another process.

javadoc: error - Error writing highlight.js license: C:\Users\aheredia\cdcl\build\docs\javadoc\internal\highlight-LICENSE.txt: The process cannot access the file because it is being used by another process.

javadoc: error - Error writing highlight.js style 'default': C:\Users\aheredia\cdcl\build\docs\javadoc\internal\highlight.css: The process cannot access the file because it is being used by another process.

My build.gradle

plugins {
  id "org.jdrupes.mdoclet" version "1.0.5"
}
.
.
.
task internalJavadoc(type: Javadoc) {
    classpath = files( project.sourceSets.main.compileClasspath )
    destinationDir = new File("${project.buildDir}/docs/javadoc/internal")
    maxMemory = '256m'
    source project.sourceSets.main.allJava
    options.addStringOption('Xdoclint:none', '-quiet')
    group = 'documentation'
    options.stylesheetFile = rootProject.file('config/javadoc/stylesheet.css')
    options.doclet = 'org.jdrupes.mdoclet'

**Comment by mnlipp** [comment]
This is hard for me to reproduce, because I don't have a Windows machine.

I have, nevertheless, checked that the files which are copied here are properly closed. They are. So there is no apparent reason for any lock.

It may be a gradle problem&mdash;it opens these files as well. I know about at least one other plugin where a [locking issue](https://github.com/ajoberstar/gradle-git-publish/issues/68) depends on the gradle version used. From what I have read, gradle 5.0 should be okay and then 5.3, but nothing in between. Which gradle version are you using?

**Comment by bertoso** [comment]
5.2.1

**Comment by mnlipp** [comment]
Well, then try 5.0 and 5.3 to check if it is a gradle issue.

**Comment by bertoso** [comment]
I was able to build using Ubuntu VM without changing gradle version. Must be an issue with Windows box hmmm.

**Comment by bertoso** [comment]
One more question. How to configure in gradle if I want to use custom highlight.css?

**Comment by mnlipp** [comment]
Configuring this is currently not supported. Why don't you simply add a `doLast` (or another task) that overwrites the default files with your versions?

**Comment by nedtwigg** [comment]
Confirmed broken (windows only) in gradle `6.4.1` with `org.jdrupes.mdoclet` version `1.0.9`.

**Comment by nedtwigg** [comment]
I believe the problem is here:

https://github.com/mnlipp/jdrupes-mdoclet/blob/4161862da212b7012d462a3f082c21fb5b858e2f/mdoclet/src/org/jdrupes/mdoclet/MDoclet.java#L285-L293

Line 287 opens an OutputStream, but it isn't used, on line 291 `Files.copy` is used instead.  Windows is less forgiving about filesystem conflicts than unix.

**Comment by mnlipp** [comment]
Yours to test on Windows (mdoclet 1.0.10)

**Comment by nedtwigg** [comment]
Awesome, thanks!  Confirmed fixed.
