### ISSUE TITLE
@see tags different rendering in 2.0.0

### ISSUE THREAD

**Issue by agologan** [mnlipp/jdrupes-mdoclet#12]
After updating to 2.0.0 @see tags no longer render as `@see <a href="http://www.example.com/">LABEL</a>`.

This may be due to the fact we split the field with a new line as seen here:
https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationRequest.java

New:
https://javadoc.io/doc/net.openid/appauth/0.11.0/net/openid/appauth/AuthorizationRequest.Prompt.html
Old:
https://javadoc.io/doc/net.openid/appauth/0.10.0/net/openid/appauth/AuthorizationRequest.Prompt.html

After some testing only this format works: `@see "[Example](http://www.example.com/)"`  (singleline)

Our integration: https://github.com/openid/AppAuth-Android/commit/61ca40d58d1067175f736320c2063f16b263773d?diff=split

This might not be a mdoclet issue but I don't know enough javadoc to say for certain so any feedback would be appreciated.

**Comment by mnlipp** [comment]
Processing is done in completely different ways. The new version uses "pre-parsed" tag-trees from the standard doclet and obviously the standard parser does not allow `@see` tags to span multiple lines.

When you look at the javadoc [description](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html) (I somehow fail to find that page for Java 11) you'll find that e.g. for `@param` tags continuation is specified explicitly ("you can continue the description onto multiple lines"), but this is not specified for `@see`.

So I assume that multi-line `@see` worked in the old version simply because parsing the comment was done by mdoclet, not by the standard doclet.
