### ISSUE TITLE
org.jdrupes.mdoclet:doclet:1.0.9 is missing from mavencentral

### ISSUE THREAD

**Issue by nedtwigg** [mnlipp/jdrupes-mdoclet#5]
- it is present in bintray: https://bintray.com/mnlipp/jdrupes/org.jdrupes.mdoclet%3Adoclet
- but not on maven central: https://search.maven.org/artifact/org.jdrupes.mdoclet/doclet

I think you can click the "sync to mavencentral" button in the Bintray web UI to solve the problem.

**Comment by mnlipp** [comment]
I pushed the sync button. Let's hope it helps. It's nice of sonatype to provide maven central, but uploading to it is a damned nuisance. It fails approx. 1 out of 3 times. That's why I have switched to uploading to bintray with automatic sync to sonatype (which seems to fail a bit less often) and not checking if it succeeds. But I admit that I haven't updated all my github pages to clearly state that bintray is now the preferred repository.
