### ISSUE TITLE
No longer published to gradle plugin repository

### ISSUE THREAD

**Issue by nedtwigg** [mnlipp/jdrupes-mdoclet#9]
The latest version available at https://plugins.gradle.org/plugin/org.jdrupes.mdoclet is `1.0.10`.

MavenCentral does have `2.0.0`, but you can't just throw it into the `plugins` block:  https://search.maven.org/artifact/org.jdrupes.mdoclet/doclet

**Comment by mnlipp** [comment]
This is intentional. Well, not really "intentional". But the point is that the plugin provided with 1.0.10 created some configurations to be used with the gradle javadoc task. 

As decribed in the [docs](https://mnlipp.github.io/jdrupes-mdoclet/javadoc/), version 2.0.0 can only be used by effectively configuring a program invocation. Having a plugin for that would be nice, but this came down to reimplementing gradle's javadoc task, at least until the [fork issue](https://github.com/gradle/gradle/issues/16602) is fixed.

So, sorry, but currently no plugin, only a JavaExec task that must be configured similar to a javadoc invocation from the command line.
